server:
  port: 8080

spring:
  jpa:
    open-in-view: false
  profiles:
    group:
      "local": "local-api"
      "test": "test-api"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    root: info

